In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
pd.set_option('expand_frame_repr',False)

In [2]:
df = pd.read_csv('Sep-Potato.csv', header=1)
df['Price Date'] = pd.to_datetime(df['Price Date'], format='%d-%b-%y')
df_cleaned = df.drop_duplicates(subset=['Price Date'])
df_sorted = df_cleaned.sort_values(by='Price Date')
Extracted_features = df_sorted[['District Name', 'Commodity', 'Min Price (Rs./Quintal)', 'Max Price (Rs./Quintal)', 'Modal Price (Rs./Quintal)', 'Price Date']]
Extracted_features.set_index('Price Date', inplace=True)
full_date = pd.date_range(start='2024-09-01', end='2024-09-30')
full_Extracted_features = Extracted_features.reindex(full_date)
full_Extracted_features['Date'] = full_date
full_Extracted_features['Max Price (Rs./Quintal)'] = full_Extracted_features['Max Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features['Min Price (Rs./Quintal)'] = full_Extracted_features['Min Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features['Modal Price (Rs./Quintal)'] = full_Extracted_features['Modal Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features['Max Price (Rs./Quintal)'] = full_Extracted_features['Max Price (Rs./Quintal)'].round(0)
full_Extracted_features.iloc[0, 2:5] = full_Extracted_features.iloc[1:3, 2:5].mean()
full_Extracted_features['District Name'], full_Extracted_features['Commodity'] = 'Ahmedabad', 'Potato'
display(full_Extracted_features)

           District Name Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date
2024-09-01     Ahmedabad    Potato                   2000.0                   2450.0                     2350.0 2024-09-01
2024-09-02     Ahmedabad    Potato                   2000.0                   2500.0                     2400.0 2024-09-02
2024-09-03     Ahmedabad    Potato                   2000.0                   2400.0                     2300.0 2024-09-03
2024-09-04     Ahmedabad    Potato                   2000.0                   2300.0                     2200.0 2024-09-04
2024-09-05     Ahmedabad    Potato                   2000.0                   2300.0                     2200.0 2024-09-05
2024-09-06     Ahmedabad    Potato                   1800.0                   2100.0                     2000.0 2024-09-06
2024-09-07     Ahmedabad    Potato                   1800.0                   2167.0                     2025.0 2024-09-07
2024-09-08     Ahmedabad    Potato                   1800.0                   2233.0                     2050.0 2024-09-08
2024-09-09     Ahmedabad    Potato                   1800.0                   2300.0                     2075.0 2024-09-09
2024-09-10     Ahmedabad    Potato                   1800.0                   2367.0                     2100.0 2024-09-10
2024-09-11     Ahmedabad    Potato                   1800.0                   2433.0                     2125.0 2024-09-11
2024-09-12     Ahmedabad    Potato                   1800.0                   2500.0                     2150.0 2024-09-12
2024-09-13     Ahmedabad    Potato                   1800.0                   2300.0                     2050.0 2024-09-13
2024-09-14     Ahmedabad    Potato                   1800.0                   2262.0                     2050.0 2024-09-14
2024-09-15     Ahmedabad    Potato                   1800.0                   2225.0                     2050.0 2024-09-15
2024-09-16     Ahmedabad    Potato                   1800.0                   2188.0                     2050.0 2024-09-16
2024-09-17     Ahmedabad    Potato                   1800.0                   2150.0                     2050.0 2024-09-17
2024-09-18     Ahmedabad    Potato                   1800.0                   2150.0                     2050.0 2024-09-18
2024-09-19     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-19
2024-09-20     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-20
2024-09-21     Ahmedabad    Potato                   1800.0                   2400.0                     2200.0 2024-09-21
2024-09-22     Ahmedabad    Potato                   1800.0                   2300.0                     2150.0 2024-09-22
2024-09-23     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-23
2024-09-24     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-24
2024-09-25     Ahmedabad    Potato                   2000.0                   2800.0                     2500.0 2024-09-25
2024-09-26     Ahmedabad    Potato                   1800.0                   2800.0                     2600.0 2024-09-26
2024-09-27     Ahmedabad    Potato                   1800.0                   2800.0                     2600.0 2024-09-27
2024-09-28     Ahmedabad    Potato                   1800.0                   3000.0                     2700.0 2024-09-28
2024-09-29     Ahmedabad    Potato                   1800.0                   2900.0                     2650.0 2024-09-29
2024-09-30     Ahmedabad    Potato                   1800.0                   2800.0                     2600.0 2024-09-30

In [3]:
df1 = pd.read_csv('Sep-onion.csv', header=1)
df1['Price Date'] = pd.to_datetime(df1['Price Date'], format='%d-%b-%y')
df1_cleaned = df1.drop_duplicates(subset=['Price Date'])
df1_sorted = df1_cleaned.sort_values(by='Price Date')
Extracted_features1 = df1_sorted[['District Name', 'Commodity', 'Min Price (Rs./Quintal)', 'Max Price (Rs./Quintal)', 'Modal Price (Rs./Quintal)', 'Price Date']]
Extracted_features1.set_index('Price Date', inplace=True)
full_date1 = pd.date_range(start='2024-09-01', end='2024-09-30')
full_Extracted_features1 = Extracted_features1.reindex(full_date1)
full_Extracted_features1['Date'] = full_date1
full_Extracted_features1['Max Price (Rs./Quintal)'] = full_Extracted_features1['Max Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features1['Min Price (Rs./Quintal)'] = full_Extracted_features1['Min Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features1['Modal Price (Rs./Quintal)'] = full_Extracted_features1['Modal Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features1.iloc[0, 2:5] = full_Extracted_features1.iloc[1:4, 2:5].mean()
full_Extracted_features1['Modal Price (Rs./Quintal)'] = full_Extracted_features1['Modal Price (Rs./Quintal)'].round(0)
full_Extracted_features1['Max Price (Rs./Quintal)'] = full_Extracted_features1['Max Price (Rs./Quintal)'].round(0)
full_Extracted_features1['District Name'], full_Extracted_features1['Commodity'] = 'Ahmedabad', 'Onion'
display(full_Extracted_features1)

           District Name Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date
2024-09-01     Ahmedabad     Onion                   2400.0                   3967.0                     3733.0 2024-09-01
2024-09-02     Ahmedabad     Onion                   2500.0                   3800.0                     3600.0 2024-09-02
2024-09-03     Ahmedabad     Onion                   2500.0                   4100.0                     3900.0 2024-09-03
2024-09-04     Ahmedabad     Onion                   2200.0                   4000.0                     3700.0 2024-09-04
2024-09-05     Ahmedabad     Onion                   2200.0                   4000.0                     3750.0 2024-09-05
2024-09-06     Ahmedabad     Onion                   2000.0                   4000.0                     3750.0 2024-09-06
2024-09-07     Ahmedabad     Onion                   2000.0                   3967.0                     3608.0 2024-09-07
2024-09-08     Ahmedabad     Onion                   2000.0                   3933.0                     3467.0 2024-09-08
2024-09-09     Ahmedabad     Onion                   2000.0                   3900.0                     3325.0 2024-09-09
2024-09-10     Ahmedabad     Onion                   2000.0                   3867.0                     3183.0 2024-09-10
2024-09-11     Ahmedabad     Onion                   2000.0                   3833.0                     3042.0 2024-09-11
2024-09-12     Ahmedabad     Onion                   2000.0                   3800.0                     2900.0 2024-09-12
2024-09-13     Ahmedabad     Onion                   2000.0                   4000.0                     3000.0 2024-09-13
2024-09-14     Ahmedabad     Onion                   2062.5                   4050.0                     3238.0 2024-09-14
2024-09-15     Ahmedabad     Onion                   2125.0                   4100.0                     3475.0 2024-09-15
2024-09-16     Ahmedabad     Onion                   2187.5                   4150.0                     3712.0 2024-09-16
2024-09-17     Ahmedabad     Onion                   2250.0                   4200.0                     3950.0 2024-09-17
2024-09-18     Ahmedabad     Onion                   2250.0                   4200.0                     3950.0 2024-09-18
2024-09-19     Ahmedabad     Onion                   3000.0                   4500.0                     4000.0 2024-09-19
2024-09-20     Ahmedabad     Onion                   2000.0                   4500.0                     4250.0 2024-09-20
2024-09-21     Ahmedabad     Onion                   2500.0                   4500.0                     4000.0 2024-09-21
2024-09-22     Ahmedabad     Onion                   2500.0                   4500.0                     4125.0 2024-09-22
2024-09-23     Ahmedabad     Onion                   2500.0                   4500.0                     4250.0 2024-09-23
2024-09-24     Ahmedabad     Onion                   2500.0                   4600.0                     4350.0 2024-09-24
2024-09-25     Ahmedabad     Onion                   2500.0                   4600.0                     3800.0 2024-09-25
2024-09-26     Ahmedabad     Onion                   2500.0                   4500.0                     4250.0 2024-09-26
2024-09-27     Ahmedabad     Onion                   2500.0                   4300.0                     4150.0 2024-09-27
2024-09-28     Ahmedabad     Onion                   2500.0                   4300.0                     4100.0 2024-09-28
2024-09-29     Ahmedabad     Onion                   2500.0                   4150.0                     3950.0 2024-09-29
2024-09-30     Ahmedabad     Onion                   2500.0                   4000.0                     3800.0 2024-09-30

In [4]:
df2 = pd.read_csv('Sep-cabbage.csv', header=1)
df2['Price Date'] = pd.to_datetime(df2['Price Date'], format='%d-%b-%y')
df2_cleaned = df2.drop_duplicates(subset=['Price Date'])
df2_sorted = df2_cleaned.sort_values(by='Price Date')
Extracted_features2 = df2_sorted[['District Name', 'Commodity', 'Min Price (Rs./Quintal)', 'Max Price (Rs./Quintal)', 'Modal Price (Rs./Quintal)', 'Price Date']]
Extracted_features2.set_index('Price Date', inplace=True)
full_date2 = pd.date_range(start='2024-09-01', end='2024-09-30')
full_Extracted_features2 = Extracted_features2.reindex(full_date2)
full_Extracted_features2['Date'] = full_date2
full_Extracted_features2['Max Price (Rs./Quintal)'] = full_Extracted_features2['Max Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features2['Min Price (Rs./Quintal)'] = full_Extracted_features2['Min Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features2['Modal Price (Rs./Quintal)'] = full_Extracted_features2['Modal Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features2.iloc[0, 2:5] = full_Extracted_features2.iloc[1:3, 2:5].mean()
full_Extracted_features2['District Name'], full_Extracted_features2['Commodity'] = 'Ahmedabad', 'Cabbage'
display(full_Extracted_features2)

           District Name Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date
2024-09-01     Ahmedabad   Cabbage                    600.0                   1750.0                     1250.0 2024-09-01
2024-09-02     Ahmedabad   Cabbage                    400.0                   1500.0                     1100.0 2024-09-02
2024-09-03     Ahmedabad   Cabbage                    800.0                   2000.0                     1400.0 2024-09-03
2024-09-04     Ahmedabad   Cabbage                   1000.0                   2000.0                     1550.0 2024-09-04
2024-09-05     Ahmedabad   Cabbage                   1200.0                   2000.0                     1700.0 2024-09-05
2024-09-06     Ahmedabad   Cabbage                    500.0                   1800.0                     1350.0 2024-09-06
2024-09-07     Ahmedabad   Cabbage                    600.0                   1840.0                     1380.0 2024-09-07
2024-09-08     Ahmedabad   Cabbage                    700.0                   1880.0                     1410.0 2024-09-08
2024-09-09     Ahmedabad   Cabbage                    800.0                   1920.0                     1440.0 2024-09-09
2024-09-10     Ahmedabad   Cabbage                    900.0                   1960.0                     1470.0 2024-09-10
2024-09-11     Ahmedabad   Cabbage                   1000.0                   2000.0                     1500.0 2024-09-11
2024-09-12     Ahmedabad   Cabbage                    700.0                   1600.0                     1150.0 2024-09-12
2024-09-13     Ahmedabad   Cabbage                   1000.0                   1800.0                     1400.0 2024-09-13
2024-09-14     Ahmedabad   Cabbage                   1200.0                   1975.0                     1612.5 2024-09-14
2024-09-15     Ahmedabad   Cabbage                   1400.0                   2150.0                     1825.0 2024-09-15
2024-09-16     Ahmedabad   Cabbage                   1600.0                   2325.0                     2037.5 2024-09-16
2024-09-17     Ahmedabad   Cabbage                   1800.0                   2500.0                     2250.0 2024-09-17
2024-09-18     Ahmedabad   Cabbage                   1200.0                   2250.0                     2150.0 2024-09-18
2024-09-19     Ahmedabad   Cabbage                   1000.0                   2200.0                     1700.0 2024-09-19
2024-09-20     Ahmedabad   Cabbage                   1300.0                   2200.0                     1950.0 2024-09-20
2024-09-21     Ahmedabad   Cabbage                   1200.0                   2300.0                     1800.0 2024-09-21
2024-09-22     Ahmedabad   Cabbage                   1350.0                   2300.0                     1825.0 2024-09-22
2024-09-23     Ahmedabad   Cabbage                   1500.0                   2300.0                     1850.0 2024-09-23
2024-09-24     Ahmedabad   Cabbage                   1250.0                   2250.0                     1825.0 2024-09-24
2024-09-25     Ahmedabad   Cabbage                   1000.0                   2200.0                     1800.0 2024-09-25
2024-09-26     Ahmedabad   Cabbage                   1400.0                   2200.0                     1900.0 2024-09-26
2024-09-27     Ahmedabad   Cabbage                   1000.0                   2000.0                     1400.0 2024-09-27
2024-09-28     Ahmedabad   Cabbage                   1000.0                   2000.0                     1700.0 2024-09-28
2024-09-29     Ahmedabad   Cabbage                   1100.0                   2200.0                     1800.0 2024-09-29
2024-09-30     Ahmedabad   Cabbage                   1200.0                   2400.0                     1900.0 2024-09-30

In [5]:
df3 = pd.read_csv('Sep-bottle gourd.csv', header=1)
df3['Price Date'] = pd.to_datetime(df3['Price Date'], format='%d-%b-%y')
df3_cleaned = df3.drop_duplicates(subset=['Price Date'])
df3_sorted =  df3_cleaned.sort_values(by='Price Date')
Extracted_features3 = df3_sorted[['District Name', 'Commodity', 'Min Price (Rs./Quintal)', 'Max Price (Rs./Quintal)', 'Modal Price (Rs./Quintal)', 'Price Date']]
Extracted_features3.set_index('Price Date', inplace=True)
full_date3 = pd.date_range(start='2024-09-01', end='2024-09-30')
full_Extracted_features3 = Extracted_features3.reindex(full_date3)
full_Extracted_features3['Date'] = full_date3
full_Extracted_features3['Max Price (Rs./Quintal)'] = full_Extracted_features3['Max Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features3['Min Price (Rs./Quintal)'] = full_Extracted_features3['Min Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features3['Modal Price (Rs./Quintal)'] = full_Extracted_features3['Modal Price (Rs./Quintal)'].interpolate(method='linear')
full_Extracted_features3.iloc[0, 2:5] = full_Extracted_features.iloc[1:3, 2:5].mean()
full_Extracted_features3['District Name'], full_Extracted_features3['Commodity'] = 'Ahmedabad', 'Bottle gourd'
display(full_Extracted_features3)

           District Name     Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date
2024-09-01     Ahmedabad  Bottle gourd                   2000.0                   2450.0                     2350.0 2024-09-01
2024-09-02     Ahmedabad  Bottle gourd                   1000.0                   5000.0                     3650.0 2024-09-02
2024-09-03     Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2450.0 2024-09-03
2024-09-04     Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2750.0 2024-09-04
2024-09-05     Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2650.0 2024-09-05
2024-09-06     Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2850.0 2024-09-06
2024-09-07     Ahmedabad  Bottle gourd                   1200.0                   4900.0                     2930.0 2024-09-07
2024-09-08     Ahmedabad  Bottle gourd                   1400.0                   4800.0                     3010.0 2024-09-08
2024-09-09     Ahmedabad  Bottle gourd                   1600.0                   4700.0                     3090.0 2024-09-09
2024-09-10     Ahmedabad  Bottle gourd                   1800.0                   4600.0                     3170.0 2024-09-10
2024-09-11     Ahmedabad  Bottle gourd                   2000.0                   4500.0                     3250.0 2024-09-11
2024-09-12     Ahmedabad  Bottle gourd                   1000.0                   3500.0                     2250.0 2024-09-12
2024-09-13     Ahmedabad  Bottle gourd                   1500.0                   4000.0                     2750.0 2024-09-13
2024-09-14     Ahmedabad  Bottle gourd                   1375.0                   3750.0                     2525.0 2024-09-14
2024-09-15     Ahmedabad  Bottle gourd                   1250.0                   3500.0                     2300.0 2024-09-15
2024-09-16     Ahmedabad  Bottle gourd                   1125.0                   3250.0                     2075.0 2024-09-16
2024-09-17     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     1850.0 2024-09-17
2024-09-18     Ahmedabad  Bottle gourd                   1000.0                   4000.0                     2350.0 2024-09-18
2024-09-19     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2200.0 2024-09-19
2024-09-20     Ahmedabad  Bottle gourd                   1000.0                   4000.0                     2500.0 2024-09-20
2024-09-21     Ahmedabad  Bottle gourd                   1000.0                   2000.0                     1800.0 2024-09-21
2024-09-22     Ahmedabad  Bottle gourd                   1000.0                   2750.0                     2075.0 2024-09-22
2024-09-23     Ahmedabad  Bottle gourd                   1000.0                   3500.0                     2350.0 2024-09-23
2024-09-24     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2175.0 2024-09-24
2024-09-25     Ahmedabad  Bottle gourd                   1000.0                   2500.0                     2000.0 2024-09-25
2024-09-26     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     1950.0 2024-09-26
2024-09-27     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2350.0 2024-09-27
2024-09-28     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2000.0 2024-09-28
2024-09-29     Ahmedabad  Bottle gourd                   1000.0                   3500.0                     2400.0 2024-09-29
2024-09-30     Ahmedabad  Bottle gourd                   1000.0                   4000.0                     2800.0 2024-09-30

In [6]:
# Weather conditin for Ahmedabad
weather = pd.read_csv('Sep-Weather-Ahmedabad.csv')
selected_features = weather[['datetime', 'tempmax', 'tempmin', 'temp', 'dew', 'humidity', 'windspeed', 'sealevelpressure']]
selected_features['Date'] = selected_features['datetime']
selected_features.set_index('datetime', inplace=True)
selected_features['Date'] = pd.to_datetime(selected_features['Date'])
display(selected_features)

C:\Users\jayesh\AppData\Local\Temp\ipykernel_19088\3632911187.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_features['Date'] = selected_features['datetime']
C:\Users\jayesh\AppData\Local\Temp\ipykernel_19088\3632911187.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_features['Date'] = pd.to_datetime(selected_features['Date'])

            tempmax  tempmin  temp   dew  humidity  windspeed  sealevelpressure       Date
datetime
2024-09-01     33.0       27  29.4  24.3      75.1       16.6            1005.2 2024-09-01
2024-09-02     29.1       25  27.3  25.1      88.1       18.0            1004.1 2024-09-02
2024-09-03     28.0       23  25.7  24.0      90.2       14.8            1004.1 2024-09-03
2024-09-04     31.0       25  26.8  24.2      86.1       45.9            1004.3 2024-09-04
2024-09-05     29.8       26  27.1  24.1      83.6       16.6            1002.7 2024-09-05
2024-09-06     31.0       25  27.5  24.6      85.0       18.4            1003.8 2024-09-06
2024-09-07     31.8       26  28.6  23.6      75.6       18.4            1005.0 2024-09-07
2024-09-08     30.3       26  28.2  24.4      79.8       18.4            1005.3 2024-09-08
2024-09-09     32.0       26  29.3  24.4      75.9       14.8            1002.9 2024-09-09
2024-09-10     30.3       26  28.2  24.6      80.9       18.4            1002.0 2024-09-10
2024-09-11     29.5       26  27.9  24.1      80.0       14.8            1002.7 2024-09-11
2024-09-12     32.0       26  28.8  23.1      72.4       22.3            1004.0 2024-09-12
2024-09-13     32.0       24  27.9  22.6      73.6       22.3            1004.9 2024-09-13
2024-09-14     31.3       24  27.2  22.7      77.6       18.4            1004.6 2024-09-14
2024-09-15     31.8       25  27.7  22.6      75.2       13.8            1005.7 2024-09-15
2024-09-16     32.0       25  28.2  21.8      69.8       14.8            1007.1 2024-09-16
2024-09-17     32.0       25  28.7  21.5      66.5       13.0            1007.4 2024-09-17
2024-09-18     32.8       26  28.9  22.6      69.6       13.0            1005.1 2024-09-18
2024-09-19     33.0       26  29.3  22.8      69.2       16.6            1005.4 2024-09-19
2024-09-20     34.0       26  29.7  23.2      68.7       18.4            1005.6 2024-09-20
2024-09-21     33.1       26  29.8  23.2      68.8       16.6            1006.7 2024-09-21
2024-09-22     34.0       27  30.1  23.3      67.8       16.6            1006.4 2024-09-22
2024-09-23     34.0       27  30.3  23.8      69.2       18.4            1005.7 2024-09-23
2024-09-24     35.0       27  30.3  24.4      71.3       15.8            1003.8 2024-09-24
2024-09-25     35.0       24  29.1  24.5      77.0       18.4            1002.8 2024-09-25
2024-09-26     32.0       23  26.8  23.9      84.6       27.7            1002.3 2024-09-26
2024-09-27     27.0       25  25.8  24.0      89.9       14.8            1002.9 2024-09-27
2024-09-28     29.0       24  25.8  23.3      86.3       13.0            1005.6 2024-09-28
2024-09-29     29.0       24  26.4  23.7      85.5       11.2            1008.5 2024-09-29
2024-09-30     32.0       24  28.2  23.6      76.9       14.8            1009.4 2024-09-30

In [8]:
Potato = full_Extracted_features.merge(selected_features, on='Date')
display(Potato)
Onion = full_Extracted_features1.merge(selected_features, on='Date')
display(Onion)
Cabbage = full_Extracted_features2.merge(selected_features, on='Date')
display(Cabbage)
Bottle_gourd  = full_Extracted_features3.merge(selected_features, on='Date')
display(Bottle_gourd)

   District Name Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date  tempmax  tempmin  temp   dew  humidity  windspeed  sealevelpressure
0      Ahmedabad    Potato                   2000.0                   2450.0                     2350.0 2024-09-01     33.0       27  29.4  24.3      75.1       16.6            1005.2
1      Ahmedabad    Potato                   2000.0                   2500.0                     2400.0 2024-09-02     29.1       25  27.3  25.1      88.1       18.0            1004.1
2      Ahmedabad    Potato                   2000.0                   2400.0                     2300.0 2024-09-03     28.0       23  25.7  24.0      90.2       14.8            1004.1
3      Ahmedabad    Potato                   2000.0                   2300.0                     2200.0 2024-09-04     31.0       25  26.8  24.2      86.1       45.9            1004.3
4      Ahmedabad    Potato                   2000.0                   2300.0                     2200.0 2024-09-05     29.8       26  27.1  24.1      83.6       16.6            1002.7
5      Ahmedabad    Potato                   1800.0                   2100.0                     2000.0 2024-09-06     31.0       25  27.5  24.6      85.0       18.4            1003.8
6      Ahmedabad    Potato                   1800.0                   2167.0                     2025.0 2024-09-07     31.8       26  28.6  23.6      75.6       18.4            1005.0
7      Ahmedabad    Potato                   1800.0                   2233.0                     2050.0 2024-09-08     30.3       26  28.2  24.4      79.8       18.4            1005.3
8      Ahmedabad    Potato                   1800.0                   2300.0                     2075.0 2024-09-09     32.0       26  29.3  24.4      75.9       14.8            1002.9
9      Ahmedabad    Potato                   1800.0                   2367.0                     2100.0 2024-09-10     30.3       26  28.2  24.6      80.9       18.4            1002.0
10     Ahmedabad    Potato                   1800.0                   2433.0                     2125.0 2024-09-11     29.5       26  27.9  24.1      80.0       14.8            1002.7
11     Ahmedabad    Potato                   1800.0                   2500.0                     2150.0 2024-09-12     32.0       26  28.8  23.1      72.4       22.3            1004.0
12     Ahmedabad    Potato                   1800.0                   2300.0                     2050.0 2024-09-13     32.0       24  27.9  22.6      73.6       22.3            1004.9
13     Ahmedabad    Potato                   1800.0                   2262.0                     2050.0 2024-09-14     31.3       24  27.2  22.7      77.6       18.4            1004.6
14     Ahmedabad    Potato                   1800.0                   2225.0                     2050.0 2024-09-15     31.8       25  27.7  22.6      75.2       13.8            1005.7
15     Ahmedabad    Potato                   1800.0                   2188.0                     2050.0 2024-09-16     32.0       25  28.2  21.8      69.8       14.8            1007.1
16     Ahmedabad    Potato                   1800.0                   2150.0                     2050.0 2024-09-17     32.0       25  28.7  21.5      66.5       13.0            1007.4
17     Ahmedabad    Potato                   1800.0                   2150.0                     2050.0 2024-09-18     32.8       26  28.9  22.6      69.6       13.0            1005.1
18     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-19     33.0       26  29.3  22.8      69.2       16.6            1005.4
19     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-20     34.0       26  29.7  23.2      68.7       18.4            1005.6
20     Ahmedabad    Potato                   1800.0                   2400.0                     2200.0 2024-09-21     33.1       26  29.8  23.2      68.8       16.6            1006.7
21     Ahmedabad    Potato                   1800.0                   2300.0                     2150.0 2024-09-22     34.0       27  30.1  23.3      67.8       16.6            1006.4
22     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-23     34.0       27  30.3  23.8      69.2       18.4            1005.7
23     Ahmedabad    Potato                   1800.0                   2200.0                     2100.0 2024-09-24     35.0       27  30.3  24.4      71.3       15.8            1003.8
24     Ahmedabad    Potato                   2000.0                   2800.0                     2500.0 2024-09-25     35.0       24  29.1  24.5      77.0       18.4            1002.8
25     Ahmedabad    Potato                   1800.0                   2800.0                     2600.0 2024-09-26     32.0       23  26.8  23.9      84.6       27.7            1002.3
26     Ahmedabad    Potato                   1800.0                   2800.0                     2600.0 2024-09-27     27.0       25  25.8  24.0      89.9       14.8            1002.9
27     Ahmedabad    Potato                   1800.0                   3000.0                     2700.0 2024-09-28     29.0       24  25.8  23.3      86.3       13.0            1005.6
28     Ahmedabad    Potato                   1800.0                   2900.0                     2650.0 2024-09-29     29.0       24  26.4  23.7      85.5       11.2            1008.5
29     Ahmedabad    Potato                   1800.0                   2800.0                     2600.0 2024-09-30     32.0       24  28.2  23.6      76.9       14.8            1009.4

   District Name Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date  tempmax  tempmin  temp   dew  humidity  windspeed  sealevelpressure
0      Ahmedabad     Onion                   2400.0                   3967.0                     3733.0 2024-09-01     33.0       27  29.4  24.3      75.1       16.6            1005.2
1      Ahmedabad     Onion                   2500.0                   3800.0                     3600.0 2024-09-02     29.1       25  27.3  25.1      88.1       18.0            1004.1
2      Ahmedabad     Onion                   2500.0                   4100.0                     3900.0 2024-09-03     28.0       23  25.7  24.0      90.2       14.8            1004.1
3      Ahmedabad     Onion                   2200.0                   4000.0                     3700.0 2024-09-04     31.0       25  26.8  24.2      86.1       45.9            1004.3
4      Ahmedabad     Onion                   2200.0                   4000.0                     3750.0 2024-09-05     29.8       26  27.1  24.1      83.6       16.6            1002.7
5      Ahmedabad     Onion                   2000.0                   4000.0                     3750.0 2024-09-06     31.0       25  27.5  24.6      85.0       18.4            1003.8
6      Ahmedabad     Onion                   2000.0                   3967.0                     3608.0 2024-09-07     31.8       26  28.6  23.6      75.6       18.4            1005.0
7      Ahmedabad     Onion                   2000.0                   3933.0                     3467.0 2024-09-08     30.3       26  28.2  24.4      79.8       18.4            1005.3
8      Ahmedabad     Onion                   2000.0                   3900.0                     3325.0 2024-09-09     32.0       26  29.3  24.4      75.9       14.8            1002.9
9      Ahmedabad     Onion                   2000.0                   3867.0                     3183.0 2024-09-10     30.3       26  28.2  24.6      80.9       18.4            1002.0
10     Ahmedabad     Onion                   2000.0                   3833.0                     3042.0 2024-09-11     29.5       26  27.9  24.1      80.0       14.8            1002.7
11     Ahmedabad     Onion                   2000.0                   3800.0                     2900.0 2024-09-12     32.0       26  28.8  23.1      72.4       22.3            1004.0
12     Ahmedabad     Onion                   2000.0                   4000.0                     3000.0 2024-09-13     32.0       24  27.9  22.6      73.6       22.3            1004.9
13     Ahmedabad     Onion                   2062.5                   4050.0                     3238.0 2024-09-14     31.3       24  27.2  22.7      77.6       18.4            1004.6
14     Ahmedabad     Onion                   2125.0                   4100.0                     3475.0 2024-09-15     31.8       25  27.7  22.6      75.2       13.8            1005.7
15     Ahmedabad     Onion                   2187.5                   4150.0                     3712.0 2024-09-16     32.0       25  28.2  21.8      69.8       14.8            1007.1
16     Ahmedabad     Onion                   2250.0                   4200.0                     3950.0 2024-09-17     32.0       25  28.7  21.5      66.5       13.0            1007.4
17     Ahmedabad     Onion                   2250.0                   4200.0                     3950.0 2024-09-18     32.8       26  28.9  22.6      69.6       13.0            1005.1
18     Ahmedabad     Onion                   3000.0                   4500.0                     4000.0 2024-09-19     33.0       26  29.3  22.8      69.2       16.6            1005.4
19     Ahmedabad     Onion                   2000.0                   4500.0                     4250.0 2024-09-20     34.0       26  29.7  23.2      68.7       18.4            1005.6
20     Ahmedabad     Onion                   2500.0                   4500.0                     4000.0 2024-09-21     33.1       26  29.8  23.2      68.8       16.6            1006.7
21     Ahmedabad     Onion                   2500.0                   4500.0                     4125.0 2024-09-22     34.0       27  30.1  23.3      67.8       16.6            1006.4
22     Ahmedabad     Onion                   2500.0                   4500.0                     4250.0 2024-09-23     34.0       27  30.3  23.8      69.2       18.4            1005.7
23     Ahmedabad     Onion                   2500.0                   4600.0                     4350.0 2024-09-24     35.0       27  30.3  24.4      71.3       15.8            1003.8
24     Ahmedabad     Onion                   2500.0                   4600.0                     3800.0 2024-09-25     35.0       24  29.1  24.5      77.0       18.4            1002.8
25     Ahmedabad     Onion                   2500.0                   4500.0                     4250.0 2024-09-26     32.0       23  26.8  23.9      84.6       27.7            1002.3
26     Ahmedabad     Onion                   2500.0                   4300.0                     4150.0 2024-09-27     27.0       25  25.8  24.0      89.9       14.8            1002.9
27     Ahmedabad     Onion                   2500.0                   4300.0                     4100.0 2024-09-28     29.0       24  25.8  23.3      86.3       13.0            1005.6
28     Ahmedabad     Onion                   2500.0                   4150.0                     3950.0 2024-09-29     29.0       24  26.4  23.7      85.5       11.2            1008.5
29     Ahmedabad     Onion                   2500.0                   4000.0                     3800.0 2024-09-30     32.0       24  28.2  23.6      76.9       14.8            1009.4

   District Name Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date  tempmax  tempmin  temp   dew  humidity  windspeed  sealevelpressure
0      Ahmedabad   Cabbage                    600.0                   1750.0                     1250.0 2024-09-01     33.0       27  29.4  24.3      75.1       16.6            1005.2
1      Ahmedabad   Cabbage                    400.0                   1500.0                     1100.0 2024-09-02     29.1       25  27.3  25.1      88.1       18.0            1004.1
2      Ahmedabad   Cabbage                    800.0                   2000.0                     1400.0 2024-09-03     28.0       23  25.7  24.0      90.2       14.8            1004.1
3      Ahmedabad   Cabbage                   1000.0                   2000.0                     1550.0 2024-09-04     31.0       25  26.8  24.2      86.1       45.9            1004.3
4      Ahmedabad   Cabbage                   1200.0                   2000.0                     1700.0 2024-09-05     29.8       26  27.1  24.1      83.6       16.6            1002.7
5      Ahmedabad   Cabbage                    500.0                   1800.0                     1350.0 2024-09-06     31.0       25  27.5  24.6      85.0       18.4            1003.8
6      Ahmedabad   Cabbage                    600.0                   1840.0                     1380.0 2024-09-07     31.8       26  28.6  23.6      75.6       18.4            1005.0
7      Ahmedabad   Cabbage                    700.0                   1880.0                     1410.0 2024-09-08     30.3       26  28.2  24.4      79.8       18.4            1005.3
8      Ahmedabad   Cabbage                    800.0                   1920.0                     1440.0 2024-09-09     32.0       26  29.3  24.4      75.9       14.8            1002.9
9      Ahmedabad   Cabbage                    900.0                   1960.0                     1470.0 2024-09-10     30.3       26  28.2  24.6      80.9       18.4            1002.0
10     Ahmedabad   Cabbage                   1000.0                   2000.0                     1500.0 2024-09-11     29.5       26  27.9  24.1      80.0       14.8            1002.7
11     Ahmedabad   Cabbage                    700.0                   1600.0                     1150.0 2024-09-12     32.0       26  28.8  23.1      72.4       22.3            1004.0
12     Ahmedabad   Cabbage                   1000.0                   1800.0                     1400.0 2024-09-13     32.0       24  27.9  22.6      73.6       22.3            1004.9
13     Ahmedabad   Cabbage                   1200.0                   1975.0                     1612.5 2024-09-14     31.3       24  27.2  22.7      77.6       18.4            1004.6
14     Ahmedabad   Cabbage                   1400.0                   2150.0                     1825.0 2024-09-15     31.8       25  27.7  22.6      75.2       13.8            1005.7
15     Ahmedabad   Cabbage                   1600.0                   2325.0                     2037.5 2024-09-16     32.0       25  28.2  21.8      69.8       14.8            1007.1
16     Ahmedabad   Cabbage                   1800.0                   2500.0                     2250.0 2024-09-17     32.0       25  28.7  21.5      66.5       13.0            1007.4
17     Ahmedabad   Cabbage                   1200.0                   2250.0                     2150.0 2024-09-18     32.8       26  28.9  22.6      69.6       13.0            1005.1
18     Ahmedabad   Cabbage                   1000.0                   2200.0                     1700.0 2024-09-19     33.0       26  29.3  22.8      69.2       16.6            1005.4
19     Ahmedabad   Cabbage                   1300.0                   2200.0                     1950.0 2024-09-20     34.0       26  29.7  23.2      68.7       18.4            1005.6
20     Ahmedabad   Cabbage                   1200.0                   2300.0                     1800.0 2024-09-21     33.1       26  29.8  23.2      68.8       16.6            1006.7
21     Ahmedabad   Cabbage                   1350.0                   2300.0                     1825.0 2024-09-22     34.0       27  30.1  23.3      67.8       16.6            1006.4
22     Ahmedabad   Cabbage                   1500.0                   2300.0                     1850.0 2024-09-23     34.0       27  30.3  23.8      69.2       18.4            1005.7
23     Ahmedabad   Cabbage                   1250.0                   2250.0                     1825.0 2024-09-24     35.0       27  30.3  24.4      71.3       15.8            1003.8
24     Ahmedabad   Cabbage                   1000.0                   2200.0                     1800.0 2024-09-25     35.0       24  29.1  24.5      77.0       18.4            1002.8
25     Ahmedabad   Cabbage                   1400.0                   2200.0                     1900.0 2024-09-26     32.0       23  26.8  23.9      84.6       27.7            1002.3
26     Ahmedabad   Cabbage                   1000.0                   2000.0                     1400.0 2024-09-27     27.0       25  25.8  24.0      89.9       14.8            1002.9
27     Ahmedabad   Cabbage                   1000.0                   2000.0                     1700.0 2024-09-28     29.0       24  25.8  23.3      86.3       13.0            1005.6
28     Ahmedabad   Cabbage                   1100.0                   2200.0                     1800.0 2024-09-29     29.0       24  26.4  23.7      85.5       11.2            1008.5
29     Ahmedabad   Cabbage                   1200.0                   2400.0                     1900.0 2024-09-30     32.0       24  28.2  23.6      76.9       14.8            1009.4

   District Name     Commodity  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  Modal Price (Rs./Quintal)       Date  tempmax  tempmin  temp   dew  humidity  windspeed  sealevelpressure
0      Ahmedabad  Bottle gourd                   2000.0                   2450.0                     2350.0 2024-09-01     33.0       27  29.4  24.3      75.1       16.6            1005.2
1      Ahmedabad  Bottle gourd                   1000.0                   5000.0                     3650.0 2024-09-02     29.1       25  27.3  25.1      88.1       18.0            1004.1
2      Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2450.0 2024-09-03     28.0       23  25.7  24.0      90.2       14.8            1004.1
3      Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2750.0 2024-09-04     31.0       25  26.8  24.2      86.1       45.9            1004.3
4      Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2650.0 2024-09-05     29.8       26  27.1  24.1      83.6       16.6            1002.7
5      Ahmedabad  Bottle gourd                   1000.0                   5000.0                     2850.0 2024-09-06     31.0       25  27.5  24.6      85.0       18.4            1003.8
6      Ahmedabad  Bottle gourd                   1200.0                   4900.0                     2930.0 2024-09-07     31.8       26  28.6  23.6      75.6       18.4            1005.0
7      Ahmedabad  Bottle gourd                   1400.0                   4800.0                     3010.0 2024-09-08     30.3       26  28.2  24.4      79.8       18.4            1005.3
8      Ahmedabad  Bottle gourd                   1600.0                   4700.0                     3090.0 2024-09-09     32.0       26  29.3  24.4      75.9       14.8            1002.9
9      Ahmedabad  Bottle gourd                   1800.0                   4600.0                     3170.0 2024-09-10     30.3       26  28.2  24.6      80.9       18.4            1002.0
10     Ahmedabad  Bottle gourd                   2000.0                   4500.0                     3250.0 2024-09-11     29.5       26  27.9  24.1      80.0       14.8            1002.7
11     Ahmedabad  Bottle gourd                   1000.0                   3500.0                     2250.0 2024-09-12     32.0       26  28.8  23.1      72.4       22.3            1004.0
12     Ahmedabad  Bottle gourd                   1500.0                   4000.0                     2750.0 2024-09-13     32.0       24  27.9  22.6      73.6       22.3            1004.9
13     Ahmedabad  Bottle gourd                   1375.0                   3750.0                     2525.0 2024-09-14     31.3       24  27.2  22.7      77.6       18.4            1004.6
14     Ahmedabad  Bottle gourd                   1250.0                   3500.0                     2300.0 2024-09-15     31.8       25  27.7  22.6      75.2       13.8            1005.7
15     Ahmedabad  Bottle gourd                   1125.0                   3250.0                     2075.0 2024-09-16     32.0       25  28.2  21.8      69.8       14.8            1007.1
16     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     1850.0 2024-09-17     32.0       25  28.7  21.5      66.5       13.0            1007.4
17     Ahmedabad  Bottle gourd                   1000.0                   4000.0                     2350.0 2024-09-18     32.8       26  28.9  22.6      69.6       13.0            1005.1
18     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2200.0 2024-09-19     33.0       26  29.3  22.8      69.2       16.6            1005.4
19     Ahmedabad  Bottle gourd                   1000.0                   4000.0                     2500.0 2024-09-20     34.0       26  29.7  23.2      68.7       18.4            1005.6
20     Ahmedabad  Bottle gourd                   1000.0                   2000.0                     1800.0 2024-09-21     33.1       26  29.8  23.2      68.8       16.6            1006.7
21     Ahmedabad  Bottle gourd                   1000.0                   2750.0                     2075.0 2024-09-22     34.0       27  30.1  23.3      67.8       16.6            1006.4
22     Ahmedabad  Bottle gourd                   1000.0                   3500.0                     2350.0 2024-09-23     34.0       27  30.3  23.8      69.2       18.4            1005.7
23     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2175.0 2024-09-24     35.0       27  30.3  24.4      71.3       15.8            1003.8
24     Ahmedabad  Bottle gourd                   1000.0                   2500.0                     2000.0 2024-09-25     35.0       24  29.1  24.5      77.0       18.4            1002.8
25     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     1950.0 2024-09-26     32.0       23  26.8  23.9      84.6       27.7            1002.3
26     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2350.0 2024-09-27     27.0       25  25.8  24.0      89.9       14.8            1002.9
27     Ahmedabad  Bottle gourd                   1000.0                   3000.0                     2000.0 2024-09-28     29.0       24  25.8  23.3      86.3       13.0            1005.6
28     Ahmedabad  Bottle gourd                   1000.0                   3500.0                     2400.0 2024-09-29     29.0       24  26.4  23.7      85.5       11.2            1008.5
29     Ahmedabad  Bottle gourd                   1000.0                   4000.0                     2800.0 2024-09-30     32.0       24  28.2  23.6      76.9       14.8            1009.4

In [9]:
X = Potato[['tempmax', 'tempmin', 'temp', 'dew', 'humidity', 'windspeed', 'sealevelpressure']]
Y = Potato['Max Price (Rs./Quintal)']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42) 

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train_scaled, y_train)
y_pred = model.predict(x_test_scaled)
predicted_price = pd.DataFrame(y_pred)
display("Predicted Prices", predicted_price)

'Predicted Prices'

         0
0  2550.59
1  2256.07
2  2446.22
3  2279.77
4  2420.31
5  2336.51

In [ ]:
plt.scatter(y_test, y_pred)
plt.xlabel('Actual Max Price')
plt.ylabel('Predicted Max Price')
plt.title('Actual vs Predicted Max Price')
plt.show()